

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

using System.Data.Entity.Core.Objects;
using System.Linq;


public partial class EDM_DBEntities : DbContext
{
    public EDM_DBEntities()
        : base("name=EDM_DBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<default_tbChucNang> default_tbChucNang { get; set; }

    public virtual DbSet<default_tbChucNang_ThaoTac> default_tbChucNang_ThaoTac { get; set; }

    public virtual DbSet<default_tbChucVu> default_tbChucVu { get; set; }

    public virtual DbSet<default_tbLoaiChiDinh> default_tbLoaiChiDinh { get; set; }

    public virtual DbSet<default_tbQuocGia> default_tbQuocGia { get; set; }

    public virtual DbSet<default_tbRang> default_tbRang { get; set; }

    public virtual DbSet<default_tbTinhTrangRang> default_tbTinhTrangRang { get; set; }

    public virtual DbSet<tbBacSy> tbBacSies { get; set; }

    public virtual DbSet<tbBenhNhan> tbBenhNhans { get; set; }

    public virtual DbSet<tbBenhNhanBacSyPhuTrach> tbBenhNhanBacSyPhuTraches { get; set; }

    public virtual DbSet<tbBenhNhanNguoiThan> tbBenhNhanNguoiThans { get; set; }

    public virtual DbSet<tbBenhNhanTienSuBenh> tbBenhNhanTienSuBenhs { get; set; }

    public virtual DbSet<tbCanBenh> tbCanBenhs { get; set; }

    public virtual DbSet<tbCoCauToChuc> tbCoCauToChucs { get; set; }

    public virtual DbSet<tbDonViSuDung> tbDonViSuDungs { get; set; }

    public virtual DbSet<tbKieuNguoiDung> tbKieuNguoiDungs { get; set; }

    public virtual DbSet<tbLichDieuTri> tbLichDieuTris { get; set; }

    public virtual DbSet<tbLichDieuTri_AnhMoTa> tbLichDieuTri_AnhMoTa { get; set; }

    public virtual DbSet<tbLichHen> tbLichHens { get; set; }

    public virtual DbSet<tbLoaiChiDinhTepDinhKem> tbLoaiChiDinhTepDinhKems { get; set; }

    public virtual DbSet<tbLoaiThuThuat> tbLoaiThuThuats { get; set; }

    public virtual DbSet<tbNguoiDung> tbNguoiDungs { get; set; }

    public virtual DbSet<tbNguoiDungKieuNguoiDung> tbNguoiDungKieuNguoiDungs { get; set; }

    public virtual DbSet<tbPhieuKham> tbPhieuKhams { get; set; }

    public virtual DbSet<tbThanhToan> tbThanhToans { get; set; }

    public virtual DbSet<tbThuThuat> tbThuThuats { get; set; }

    public virtual DbSet<tbTienTrinhDieuTri> tbTienTrinhDieuTris { get; set; }


    public virtual ObjectResult<Lay_TruongDuLieus_Result> Lay_TruongDuLieus(Nullable<int> maDonViSuDung)
    {

        var maDonViSuDungParameter = maDonViSuDung.HasValue ?
            new ObjectParameter("maDonViSuDung", maDonViSuDung) :
            new ObjectParameter("maDonViSuDung", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Lay_TruongDuLieus_Result>("Lay_TruongDuLieus", maDonViSuDungParameter);
    }


    public virtual int XoaDuLieuDatabase(Nullable<int> maDonViSuDung)
    {

        var maDonViSuDungParameter = maDonViSuDung.HasValue ?
            new ObjectParameter("maDonViSuDung", maDonViSuDung) :
            new ObjectParameter("maDonViSuDung", typeof(int));


        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("XoaDuLieuDatabase", maDonViSuDungParameter);
    }

}

}

