
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbLichHen
{

    public int Stt { get; set; }

    public System.Guid IdLichHen { get; set; }

    public Nullable<System.Guid> IdBacSy { get; set; }

    public Nullable<System.Guid> IdBenhNhan { get; set; }

    public Nullable<System.DateTimeOffset> NgayHen { get; set; }

    public Nullable<System.TimeSpan> ThoiGianBatDau { get; set; }

    public Nullable<System.TimeSpan> ThoiGianKetThuc { get; set; }

    public Nullable<int> LoaiDieuTri { get; set; }

    public Nullable<int> LoaiThoiGian { get; set; }

    public string LyDoHuyHen { get; set; }

    public string NoiDungKham { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> TrangThaiKham { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
