
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace EDM_DB
{

using System;
    using System.Collections.Generic;
    
public partial class tbTienTrinhDieuTri
{

    public int Stt { get; set; }

    public System.Guid IdTienTrinhDieuTri { get; set; }

    public Nullable<System.Guid> IdPhieuKham { get; set; }

    public Nullable<System.Guid> IdLichDieuTri { get; set; }

    public Nullable<System.Guid> IdBacSy { get; set; }

    public Nullable<System.Guid> IdPhuTa { get; set; }

    public Nullable<System.Guid> IdThuThuat { get; set; }

    public Nullable<System.Guid> IdTinhTrangRang { get; set; }

    public string RangSo { get; set; }

    public Nullable<int> SoLuong { get; set; }

    public Nullable<bool> KhachHangXacNhan { get; set; }

    public Nullable<long> GiaTien { get; set; }

    public Nullable<decimal> PhanTramGiamGia { get; set; }

    public Nullable<long> TongChiPhi { get; set; }

    public Nullable<int> TrangThaiDieuTri { get; set; }

    public string NoiDungThuThuat { get; set; }

    public string GhiChu { get; set; }

    public Nullable<int> TrangThai { get; set; }

    public Nullable<System.Guid> MaDonViSuDung { get; set; }

    public Nullable<System.DateTime> NgayTao { get; set; }

    public Nullable<System.Guid> IdNguoiTao { get; set; }

    public Nullable<System.DateTime> NgaySua { get; set; }

    public Nullable<System.Guid> IdNguoiSua { get; set; }

}

}
