//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDM_DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbTruongHoc
    {
        public int Stt { get; set; }
        public System.Guid IdTruongHoc { get; set; }
        public string TenTruongHoc { get; set; }
        public string TenVietTat { get; set; }
        public string Slug { get; set; }
        public string Email { get; set; }
        public string SoDienThoai { get; set; }
        public string DiaChi { get; set; }
        public string GhiChu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<System.Guid> MaDonViSuDung { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.Guid> IdNguoiTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public Nullable<System.Guid> IdNguoiSua { get; set; }
    }
}
